### PR TITLE
fix(icon): change dribble icon to quora icon

### LINKED ISSUE #3: Dribbble fa-icon need replacement by Quora fa-icon

### PR DESCRIPTION
**Pull request by daniloff200**
closes #3 

#hacktoberfest

### CODE REVIEW

**Comment by jaykay12** [comment]
@daniloff200 **Quora Icon is not showing up on fetching the changes from the PR**

screenshot from 2018-10-01 21-50-01

**Comment by daniloff200** [comment]
ah, that's because you have old FontAwesome version. This icon is available from v. 4.7
https://fontawesome.com/v4.7.0/icon/quora

**Comment by daniloff200** [comment]
If you don't like the idea, to update the whole version, I can try to cut the icon, and add it to previous version manually, but , in my opinion, it's better just update the version @jaykay12

**Comment by daniloff200** [comment]
selection_055
that's how it looks now (Instagram icon also was changed in that version)

**Comment by jaykay12** [comment]
@daniloff200 That was really helpful. 
Closes #3

**Pull request merged**
